In [6]:
import numpy as np
import torch

# Models - YOLOV1

## Build.py

`init_prob = 0.01`

`bias_value = -torch.log(torch.tensor((1. - init_prob) / init_prob))`

这里的 init_prob = 0.01 表示初始时，网络预测正类的概率设为0.01，即模型一开始假设几乎所有的输出都是负类（非目标类）。这种设置在目标检测中很常见，因为在大多数情况下，任意一个区域包含目标的概率通常很低。

In [2]:
# 这里的 init_prob = 0.01 表示初始时，网络预测正类的概率设为0.01，即模型一开始假设几乎所有的输出都是负类（非目标类）。这种设置在目标检测中很常见，因为在大多数情况下，任意一个区域包含目标的概率通常很低。
print("ss")

ss


In [ ]:
torch.log(torch.tensor(99))

In [3]:
init_prob = 0.01
bias_value = -torch.log(torch.tensor((1. - init_prob) / init_prob)) 
bias_value

tensor(-4.5951)

In [4]:
bias_value.item()

-4.595119953155518

In [7]:
# tensor.item方法：only one element tensors can be converted to Python scalars
# torch.tensor([0,1]).item()

ValueError: only one element tensors can be converted to Python scalars

In [11]:
# 构造一个类scores的数组

# 设置随机种子以便重现结果
np.random.seed(0)

# 定义参数
num_boxes = 10  # 假设有 10 个预测框
num_classes = 6  # 假设有 80 个类（如 COCO 数据集）

# 生成一个随机的 scores 矩阵
# 每个分数在 0 到 1 之间
scores = np.random.rand(num_boxes, num_classes)

In [15]:
print((scores.shape))
print(scores)
labels = np.argmax(scores, axis=1)
print(labels.shape)
print(labels)

(10, 6)
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355 ]
 [0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195]
 [0.6976312  0.06022547 0.66676672 0.67063787 0.21038256 0.1289263 ]
 [0.31542835 0.36371077 0.57019677 0.43860151 0.98837384 0.10204481]
 [0.20887676 0.16130952 0.65310833 0.2532916  0.46631077 0.24442559]]
(10,)
[1 2 1 2 3 1 2 0 4 2]


In [20]:
scores2 = scores[(np.arange(scores.shape[0]), labels)]
scores3 = scores[:, labels]

print(scores2.shape)
print(scores2)

print(scores3.shape)
print(scores3)

(10,)
[0.71518937 0.96366276 0.92559664 0.97861834 0.94466892 0.77423369
 0.94374808 0.6976312  0.98837384 0.65310833]
(10, 10)
[[0.71518937 0.60276338 0.71518937 0.60276338 0.54488318 0.71518937
  0.60276338 0.5488135  0.4236548  0.60276338]
 [0.891773   0.96366276 0.891773   0.96366276 0.38344152 0.891773
  0.96366276 0.43758721 0.79172504 0.96366276]
 [0.92559664 0.07103606 0.92559664 0.07103606 0.0871293  0.92559664
  0.07103606 0.56804456 0.0202184  0.07103606]
 [0.87001215 0.97861834 0.87001215 0.97861834 0.79915856 0.87001215
  0.97861834 0.77815675 0.46147936 0.97861834]
 [0.63992102 0.14335329 0.63992102 0.14335329 0.94466892 0.63992102
  0.14335329 0.11827443 0.52184832 0.14335329]
 [0.77423369 0.45615033 0.77423369 0.45615033 0.56843395 0.77423369
  0.45615033 0.26455561 0.0187898  0.45615033]
 [0.616934   0.94374808 0.616934   0.94374808 0.6818203  0.616934
  0.94374808 0.61209572 0.3595079  0.94374808]
 [0.06022547 0.66676672 0.06022547 0.66676672 0.67063787 0.06022547
  0

In [22]:
# Python 允许函数定义前对该函数的调用！
def A():
    B()  # 尝试调用 B 函数
    print("Function A is called")

def B():
    print("Function B is called")

A()

Function B is called
Function A is called


In [27]:
# NMS中根据置信度分数将预测框进行倒序排列

scores2 = scores[(np.arange(scores.shape[0]), labels)]


order1 = scores2.argsort()[::-1] 
torch_scores2 = torch.tensor(scores2)
order2 = torch_scores2.argsort(descending=True).numpy()

print(order1)
print(order2)
print(np.sum((order1 == order2)))


"""
numpy中array默认的数据格式是int64类型，而torch中tensor默认的数据格式是float32类型。
as_tensor和from_numpy是浅拷贝，而tensor和Tensor则是属于深拷贝，浅拷贝是直接共享内存内存空间的，这样效率更高，而深拷贝是直接创建一个新的副本。
原文链接：https://blog.csdn.net/qq_42346574/article/details/120100424
"""

[8 3 1 4 6 2 5 0 7 9]
[8 3 1 4 6 2 5 0 7 9]
10


'\nnumpy中array默认的数据格式是int64类型，而torch中tensor默认的数据格式是float32类型。\nas_tensor和from_numpy是浅拷贝，而tensor和Tensor则是属于深拷贝，浅拷贝是直接共享内存内存空间的，这样效率更高，而深拷贝是直接创建一个新的副本。\n原文链接：https://blog.csdn.net/qq_42346574/article/details/120100424\n'