In [1]:
import numpy as np
import torch

In [9]:
def singleton(cls):
    _instance = {}
    print(_instance)

    def inner():
        if cls not in _instance:
            _instance[cls] = cls()
        return _instance[cls]
    return inner
    
@singleton
class Cls(object):
    def __init__(self):
        pass

print("============")
cls1 = Cls()
cls2 = Cls()
cls3 = Cls()
print(id(cls1) == id(cls2))

{}
True


In [9]:
L=[('b',2),('a',1),('c',3),('d',4)]
# 2、利用参数 cmp 排序
sorted(L, key=lambda x: x[1])

[('a', 1), ('b', 2), ('c', 3), ('d', 4)]

In [ ]:
def desc(fun):                  # 定义装饰器函数
    def add_info():
        print("this is this.")
        fun()
        
    return add_info             #! 切记，返回函数名称

@desc
def f1():                       # 被装饰函数
    print("this is f1;")
    
f1()                            # 调用被装饰函数

# ------------------等价形式-------------------------
def add_info(fun):
    print("this is this.")
    fun()
    
def f1():                       # 被装饰函数
    print("this is f1;")
    
wrap_func = add_info(f1)
wrap_func()

In [18]:
import time
import random
import string
import functools

li = [random.choice(string.ascii_letters) for i in range(10)]
print(li)

def decorator(fun):
    #"""这是一个装饰器"""
    ##这的参数要和装饰器的参数一致,没有这一行打印的是默认的文档，
	# 就是wrapper函数的帮助文档
    @functools.wraps(fun)      
    def wrapper(*args,**kwargs):
        #"""这是一个wrapper函数"""
        t1 = time.time()
        f = fun(*args,**kwargs)
        t2 = time.time()
        print('运行时间：%.8f' %(t2 - t1))
        return f
    return wrapper

# 无参数无返回值函数1
@decorator
def con_add():
    s = ''
    for i in li:
        s += (i + ',')
    print(s)

# 无参数无返回值函数2
@decorator
def join_add():
    print(','.join(li))

# 有参数有返回值函数1
@decorator
def fun_list(n):
    """这是fun_list函数"""
    return [i * 2 for i in range(n)]

# 有参数有返回值函数2
@decorator
def fun_map(n):
    return list(map(lambda x:x*2,range(n)))

con_add()
join_add()
print(fun_list(10))
print(fun_map(10))
print(fun_list.__doc__)
print(fun_list.__name__)


['s', 'D', 's', 'E', 'k', 'O', 'Q', 'r', 'L', 'a']
s,D,s,E,k,O,Q,r,L,a,
运行时间：0.00000000
s,D,s,E,k,O,Q,r,L,a
运行时间：0.00000000
运行时间：0.00000000
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
运行时间：0.00000000
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
这是fun_list函数
fun_list


In [19]:
def decorator_a(fun):
    print('Get in decorator_a')
    def inner_a(*args, **kwargs):
        print('Get in inner_a')
        res = fun(*args, **kwargs)
        return res
    return inner_a

def decorator_b(fun):
    print('Get in decorator_b')
    def inner_b(*args, **kwargs):
        print('Get in inner_b')
        res = fun(*args, **kwargs)
        return res
    return inner_b

@decorator_a
@decorator_b
def f(x):
    print('Get in f')
    return x * 2
f(2)


Get in decorator_b
Get in decorator_a
Get in inner_a
Get in inner_b
Get in f


4

# Models - YOLOV1

## Build.py

`init_prob = 0.01`

`bias_value = -torch.log(torch.tensor((1. - init_prob) / init_prob))`

这里的 init_prob = 0.01 表示初始时，网络预测正类的概率设为0.01，即模型一开始假设几乎所有的输出都是负类（非目标类）。这种设置在目标检测中很常见，因为在大多数情况下，任意一个区域包含目标的概率通常很低。

In [2]:
# 这里的 init_prob = 0.01 表示初始时，网络预测正类的概率设为0.01，即模型一开始假设几乎所有的输出都是负类（非目标类）。这种设置在目标检测中很常见，因为在大多数情况下，任意一个区域包含目标的概率通常很低。
print("ss")

ss


In [3]:
torch.log(torch.tensor(99))

tensor(4.5951)

In [4]:
init_prob = 0.01
bias_value = -torch.log(torch.tensor((1. - init_prob) / init_prob)) 
bias_value

tensor(-4.5951)

In [5]:
bias_value.item()

-4.595119953155518

In [6]:
# tensor.item方法：only one element tensors can be converted to Python scalars
# torch.tensor([0,1]).item()

In [7]:
# 构造一个类scores的数组

# 设置随机种子以便重现结果
np.random.seed(0)

# 定义参数
num_boxes = 10  # 假设有 10 个预测框
num_classes = 6  # 假设有 80 个类（如 COCO 数据集）

# 生成一个随机的 scores 矩阵
# 每个分数在 0 到 1 之间
scores = np.random.rand(num_boxes, num_classes)

In [8]:
print((scores.shape))
print(scores)
labels = np.argmax(scores, axis=1)
print(labels.shape)
print(labels)

(10, 6)
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355 ]
 [0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195]
 [0.6976312  0.06022547 0.66676672 0.67063787 0.21038256 0.1289263 ]
 [0.31542835 0.36371077 0.57019677 0.43860151 0.98837384 0.10204481]
 [0.20887676 0.16130952 0.65310833 0.2532916  0.46631077 0.24442559]]
(10,)
[1 2 1 2 3 1 2 0 4 2]


In [9]:
scores2 = scores[(np.arange(scores.shape[0]), labels)]
scores3 = scores[:, labels]

print(scores2.shape)
print(scores2)

print(scores3.shape)
print(scores3)

(10,)
[0.71518937 0.96366276 0.92559664 0.97861834 0.94466892 0.77423369
 0.94374808 0.6976312  0.98837384 0.65310833]
(10, 10)
[[0.71518937 0.60276338 0.71518937 0.60276338 0.54488318 0.71518937
  0.60276338 0.5488135  0.4236548  0.60276338]
 [0.891773   0.96366276 0.891773   0.96366276 0.38344152 0.891773
  0.96366276 0.43758721 0.79172504 0.96366276]
 [0.92559664 0.07103606 0.92559664 0.07103606 0.0871293  0.92559664
  0.07103606 0.56804456 0.0202184  0.07103606]
 [0.87001215 0.97861834 0.87001215 0.97861834 0.79915856 0.87001215
  0.97861834 0.77815675 0.46147936 0.97861834]
 [0.63992102 0.14335329 0.63992102 0.14335329 0.94466892 0.63992102
  0.14335329 0.11827443 0.52184832 0.14335329]
 [0.77423369 0.45615033 0.77423369 0.45615033 0.56843395 0.77423369
  0.45615033 0.26455561 0.0187898  0.45615033]
 [0.616934   0.94374808 0.616934   0.94374808 0.6818203  0.616934
  0.94374808 0.61209572 0.3595079  0.94374808]
 [0.06022547 0.66676672 0.06022547 0.66676672 0.67063787 0.06022547
  0

In [10]:
# Python 允许函数定义前对该函数的调用！
def A():
    B()  # 尝试调用 B 函数
    print("Function A is called")

def B():
    print("Function B is called")

A()

Function B is called
Function A is called


In [11]:
# NMS中根据置信度分数将预测框进行倒序排列

scores2 = scores[(np.arange(scores.shape[0]), labels)]


order1 = scores2.argsort()[::-1] 
torch_scores2 = torch.tensor(scores2)
order2 = torch_scores2.argsort(descending=True).numpy()

print(order1)
print(order2)
print(np.sum((order1 == order2)))


"""
numpy中array默认的数据格式是int64类型，而torch中tensor默认的数据格式是float32类型。
as_tensor和from_numpy是浅拷贝，而tensor和Tensor则是属于深拷贝，浅拷贝是直接共享内存内存空间的，这样效率更高，而深拷贝是直接创建一个新的副本。
原文链接：https://blog.csdn.net/qq_42346574/article/details/120100424
"""

[8 3 1 4 6 2 5 0 7 9]
[8 3 1 4 6 2 5 0 7 9]
10


'\nnumpy中array默认的数据格式是int64类型，而torch中tensor默认的数据格式是float32类型。\nas_tensor和from_numpy是浅拷贝，而tensor和Tensor则是属于深拷贝，浅拷贝是直接共享内存内存空间的，这样效率更高，而深拷贝是直接创建一个新的副本。\n原文链接：https://blog.csdn.net/qq_42346574/article/details/120100424\n'

In [12]:
import numpy as np
a = np.random.beta(32.0, 32.0)
print(a)

0.4423863626941616


In [13]:
# 
a = 38
b = 32
print(a/ b)

print(int(1.1))
print(int(1.5))
print(int(1.6))

1.1875
1
1
1


In [14]:
shape1 = [22, 3, 20, 20, 10]

torch.tensor(shape1)

tensor([22,  3, 20, 20, 10])

In [15]:
import torch
from torch import nn
import torch.nn.functional as F

output = torch.randn(3,3)
output

tensor([[ 0.3721,  0.6994,  0.2631],
        [-1.1298, -0.3909,  0.3057],
        [-0.1814,  0.5260,  0.4014]])

In [16]:
active_func = nn.Sigmoid()
output = active_func(output)
print(output)

target = torch.FloatTensor([[0,1,1],[1,1,1],[0,0,0]])
loss = nn.BCELoss(reduction="mean")
loss = loss(output, target)

print(loss)

tensor([[0.5920, 0.6681, 0.5654],
        [0.2442, 0.4035, 0.5758],
        [0.4548, 0.6285, 0.5990]])
tensor(0.8056)


In [17]:
loss_obj = F.binary_cross_entropy_with_logits(output, target, reduction='none')
print(loss_obj.sum())
loss_obj_sum = F.binary_cross_entropy_with_logits(output, target, reduction='sum')
print(loss_obj_sum)
loss_obj_mean = F.binary_cross_entropy_with_logits(output, target, reduction='mean')
print(loss_obj_mean)

loss2 = nn.BCEWithLogitsLoss(reduction="mean")
loss2 = loss2(output, target)

print(loss2)

tensor(6.4713)
tensor(6.4713)
tensor(0.7190)
tensor(0.7190)


In [18]:
[1,2,3] + [4,5]

[1, 2, 3, 4, 5]

In [19]:
a = {
    "a" : 1, "b" : 2
}

list(a.keys())

['a', 'b']

In [20]:
class MyBatchNorm2d(nn.BatchNorm2d):
    def __init__(self, num_features, eps=1e-5, momentum=0.1,
                 affine=True, track_running_stats=True):
        super(MyBatchNorm2d, self).__init__(
            num_features, eps, momentum, affine, track_running_stats)

    def forward(self, input):
        # ...
        exponential_average_factor = 0.1
        
        # calculate running estimates
        if self.training:
            mean = input.mean([0, 2, 3])
            # use biased var in train
            var = input.var([0, 2, 3], unbiased=False)
            n = input.numel() / input.size(1)
            with torch.no_grad():
                self.running_mean = exponential_average_factor * mean\
                    + (1 - exponential_average_factor) * self.running_mean
                # update running_var with unbiased var
                self.running_var = exponential_average_factor * var * n / (n - 1)\
                    + (1 - exponential_average_factor) * self.running_var
        else:
            mean = self.running_mean
            var = self.running_var

        input = (input - mean[None, :, None, None]) / (torch.sqrt(var[None, :, None, None] + self.eps))
        if self.affine:
            input = input * self.weight[None, :, None, None] + self.bias[None, :, None, None]

        return input


In [21]:
# Image Example
N, C, H, W = 20, 5, 10, 15
input0 = torch.randn(N, C, H, W)

batch_norm = nn.BatchNorm2d(C)
layer_norm = nn.LayerNorm([C, H, W]) # 参数量为C*H*W*2
insta_norm1 = nn.InstanceNorm2d(5, affine=True)
group_norm1 = nn.GroupNorm(1, 5)
group_norm2 = nn.GroupNorm(5, 5)

print(batch_norm.weight.shape)
print(layer_norm.weight.shape)
print(insta_norm1.weight.shape)
print(group_norm1.weight.shape)
print(group_norm2.weight.shape)

"""
torch.Size([5])
torch.Size([5, 10, 15])
torch.Size([5])
torch.Size([5])
torch.Size([5])
"""




torch.Size([5])
torch.Size([5, 10, 15])
torch.Size([5])
torch.Size([5])
torch.Size([5])


'\ntorch.Size([5])\ntorch.Size([5, 10, 15])\ntorch.Size([5])\ntorch.Size([5])\ntorch.Size([5])\n'

In [22]:
import tensorflow as tf

x = tf.random.normal(shape=[20, 1, 5, 10, 15])
mean, var = tf.nn.moments(x, axes =[2, 3, 4], keepdims=True)
print(mean.shape)

(20, 1, 1, 1, 1)


In [33]:
import torch
import torch.nn as nn

batch_size = 3 
input_size = 2
# 假设输入特征为 x
x = torch.randn(batch_size, input_size)
# 权重和偏置
w = torch.randn(input_size, 1)
b = torch.randn(1)

# 逻辑回归输出
logits = torch.matmul(x, w) + b
predictions = torch.sigmoid(logits)

print(predictions.shape)

# 定义损失函数
criterion = nn.BCEWithLogitsLoss()

# 假设 y 是标签
y = torch.tensor([0.0, 1.0, 1.0])  # 转为浮点数
y = y.view(-1, 1)  # 修改形状为 (3, 1)
loss = criterion(predictions, y)


torch.Size([3, 1])


In [44]:
l1 = [1,4,2,3,4,1]
l2 = list(set(l1))
l2.sort(key=l1.index)
print(l2)

l1.index(4)

[1, 4, 2, 3]


1

In [45]:
import copy

a = ["张小鸡"]
b = a
c = copy.copy(a)

print(id(a))
print(id(b))
print(id(c))

2479410090624
2479410090624
2479410282368


In [52]:
import os
for root, dirs, filenmae in os.walk("F:\MarkDownFiles\ProjectsOfCamapny"):
    print(root)
    print(dirs)
    print(filenmae)

F:\MarkDownFiles\ProjectsOfCamapny
['公司项目总结.assets']
['公司项目总结.md']
F:\MarkDownFiles\ProjectsOfCamapny\公司项目总结.assets
[]
['image-20240902205420174.png', 'image-20240912132332470.png', 'image-20240925184007709.png', 'image-20240926110803304.png', 'image-20240926145848046.png', 'image-20240926145929707.png', 'image-20241008145039033.png', 'image-20241008154423190.png', 'image-20241008154432518.png', 'image-20241012163017123.png', 'image-20241023101628131.png', 'image-20241024150256436.png']


In [56]:
a = 257
b = 257
print(a is b)

False


In [57]:
c = 256
d = 256
print(c is d)

True


In [58]:
e = 256
f = e
print(e is f)

True


In [59]:
x=9
print(~x)

-10
